const SUPABASE_URL='https://jbgwdxavydhtvoqpbfmj.supabase.co';
const SUPABASE_KEY='sb_publishable_Wt8h6fNelT6zrzf-Dm8FXw_cdSGylaz';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const FACTIONS=window.TabletopContent.legacyFactionNames();
const S={user:null,profile:null,player:null,factions:[],view:'dashboard'};
const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=n=>(String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?');
const date=d=>d?new Date(d).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—';
const rate=p=>(p.games_played||0)?Math.round((p.wins||0)/(p.games_played||1)*100):0;
function notice(t,type=''){const n=$('#notice');if(n){n.textContent=t;n.className='notice '+type}}
function avatar(p,cls='avatar'){return p?.avatar_url?`<img class="${cls}" src="${esc(p.avatar_url)}" alt="">`:`<div class="${cls}">${initials(p?.display_name)}</div>`}
function errorBox(e){return `<div class="empty"><b>COMMAND ERROR</b><br>${esc(e?.message||e)}</div>`}
async function init(){try{const {data,error}=await db.auth.getSession();if(error)throw error;if(data.session)await enter(data.session.user);else showLogin()}catch(e){showLogin();setTimeout(()=>notice(e.message,'error'),0)}db.auth.onAuthStateChange(async(_,session)=>{if(session&&!S.user)await enter(session.user)})}
function showLogin(){document.body.innerHTML=`<main class="login-shell"><section class="login-card"><div class="sigil">⚔</div><div class="eyebrow">IMPERIAL WAR RECORDS</div><h1>ROUTINE <span>721</span></h1><p class="muted">BATTLE COMMAND TERMINAL</p><div class="tabs"><button id="signTab" class="active">SIGN IN</button><button id="createTab">CREATE PLAYER</button></div><form id="signForm"><label>EMAIL<input id="email" type="email" required></label><label>PASSWORD<input id="password" type="password" required></label><button class="primary" type="submit">ENTER THE WAR ROOM</button></form><form id="createForm" hidden><label>CALLSIGN<input id="callsign" maxlength="40" required></label><label>EMAIL<input id="newEmail" type="email" required></label><label>PASSWORD<input id="newPassword" type="password" minlength="6" required></label><button class="primary" type="submit">CREATE PLAYER</button></form><div id="notice" class="notice"></div></section></main>`;
$('#signForm').onsubmit=async e=>{e.preventDefault();notice('CONNECTING…');const {data,error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)return notice(error.message,'error');await enter(data.user)};
$('#createForm').onsubmit=async e=>{e.preventDefault();notice('CREATING PLAYER…');const name=$('#callsign').value.trim(),email=$('#newEmail').value.trim(),password=$('#newPassword').value;const {data,error}=await db.auth.signUp({email,password,options:{data:{display_name:name}}});if(error)return notice(error.message,'error');if(data.session)await enter(data.user);else notice('ACCOUNT CREATED — CHECK YOUR EMAIL IF CONFIRMATION IS ENABLED.','success')};
$('#signTab').onclick=()=>toggleAuth(false);$('#createTab').onclick=()=>toggleAuth(true)}
function toggleAuth(create){$('#signForm').hidden=create;$('#createForm').hidden=!create;$('#signTab').classList.toggle('active',!create);$('#createTab').classList.toggle('active',create)}
async function enter(user){S.user=user;let {data:p,error}=await db.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)return authFailure(error);if(!p){const name=user.user_metadata?.display_name||user.email.split('@')[0];const r=await db.from('profiles').insert({id:user.id,display_name:name}).select().single();if(r.error)return authFailure(r.error);p=r.data}S.profile=p;let {data:pl,error:pe}=await db.from('players').select('*').eq('user_id',user.id).maybeSingle();if(pe)return authFailure(pe);if(!pl){const r=await db.from('players').insert({user_id:user.id,display_name:p.display_name,primary_faction:null,games_played:0,wins:0,losses:0,draws:0}).select().single();if(r.error)return authFailure(r.error);pl=r.data}S.player=pl;await loadFactions();renderShell();await renderView()}
function authFailure(e){S.user=null;showLogin();setTimeout(()=>notice(e.message,'error'),0)}
async function loadFactions(){const {data,error}=await db.from('player_factions').select('faction').eq('player_id',S.player.id);S.factions=error?[]:(data||[]).map(x=>x.faction)}
function nav(v,t,i){return `<button class="nav-button" data-view="${v}"><i>${i}</i>${t}</button>`}
function renderShell(){document.body.innerHTML=`<div id="app"><header class="topbar"><div><div class="brand">ROUTINE 721</div><div class="brand-sub">IMPERIAL BATTLE COMMAND // M42</div></div><div class="user-area">${avatar(S.profile,'mini-avatar')}<span>${esc(S.profile.display_name)}</span><button id="logout" class="secondary">SIGN OUT</button></div></header><div class="layout"><aside class="sidebar"><div class="sidebar-label">COMMAND DECK</div>${nav('dashboard','WAR ROOM','⌂')}${nav('players','PLAYERS','♙')}${nav('leaderboard','LEADERBOARD','♛')}${nav('factions','FACTIONS','⚔')}${nav('groups','BATTLE GROUPS','✦')}${nav('matches','MATCHES','◈')}${nav('profile','MY PROFILE','◎')}</aside><main class="content"><div class="content-title"><div><div class="eyebrow">ACTIVE CAMPAIGN // 721</div><h1 id="pageTitle"></h1></div><div id="notice"></div></div><div id="page"></div></main></div><div id="modal" hidden></div></div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;renderView()});$('#logout').onclick=async()=>{await db.auth.signOut();S.user=null;S.profile=null;S.player=null;showLogin()}}
async function renderView(){const titles={dashboard:'WAR ROOM',players:'PLAYERS',leaderboard:'LEADERBOARD',factions:'FACTIONS',groups:'BATTLE GROUPS',matches:'MATCHES',profile:'MY PROFILE'};$('#pageTitle').textContent=titles[S.view];document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===S.view));const fn={dashboard,players,leaderboard,factions,groups,matches,profile}[S.view];$('#page').innerHTML='<div class="empty">LOADING COMMAND DATA…</div>';try{await fn($('#page'))}catch(e){$('#page').innerHTML=errorBox(e)}}
async function dashboard(c){const {data:g,error}=await db.from('games').select('*').eq('owner_user_id',S.user.id).order('played_at',{ascending:false}).limit(8);if(error)throw error;c.innerHTML=`<section class="hero"><div><div class="eyebrow">TACTICAL COMMAND</div><h2>WELCOME, ${esc(S.profile.display_name).toUpperCase()}</h2><p>Campaign record active. The Emperor watches every engagement.</p></div><button class="primary" id="recordBattle">+ RECORD BATTLE</button></section><section class="stats"><article><small>BATTLES</small><b>${S.player.games_played||0}</b></article><article><small>VICTORIES</small><b>${S.player.wins||0}</b></article><article><small>DEFEATS</small><b>${S.player.losses||0}</b></article><article><small>DRAWS</small><b>${S.player.draws||0}</b></article><article class="rate"><small>WIN RATE</small><b>${rate(S.player)}%</b></article></section><section class="panel"><div class="panel-head"><h3>RECENT BATTLE REPORTS</h3><button class="secondary" id="recordBattle2">LOG BATTLE</button></div>${g?.length?g.map(gameRow).join(''):'<div class="empty">No battles recorded. The first engagement awaits.</div>'}</section>`;$('#recordBattle').onclick=openBattle;$('#recordBattle2').onclick=openBattle}
function gameRow(x){return `<div class="game-row"><div><strong>${esc(x.opponent_name)}</strong><span>${esc(x.player_faction||'Unknown')} vs ${esc(x.opponent_faction||'Unknown')} · ${date(x.played_at)}</span></div><div><b class="result ${esc(x.result)}">${esc(x.result).toUpperCase()}</b><span>${x.player_score??'—'} VP</span></div></div>`}
async function players(c){const {data,error}=await db.from('players').select('*').order('wins',{ascending:false}).order('display_name');if(error)throw error;const {data:profiles}=await db.from('profiles').select('id,avatar_url');c.innerHTML=`<section class="panel"><div class="panel-head"><h3>IMPERIAL PERSONNEL REGISTER</h3></div><div class="player-grid">${(data||[]).map(p=>{const pr=(profiles||[]).find(x=>x.id===p.user_id);return `<article class="player-card">${avatar({display_name:p.display_name,avatar_url:pr?.avatar_url})}<h3>${esc(p.display_name)}</h3><p>${esc(p.primary_faction||'Faction unassigned')}</p><div class="player-stats"><span>${p.games_played||0} GAMES</span><strong>${p.wins||0}W / ${p.losses||0}L / ${p.draws||0}D</strong></div><div class="winrate">${rate(p)}% WIN RATE</div></article>`}).join('')||'<div class="empty">No players registered.</div>'}</div></section>`}
async function leaderboard(c){const {data,error}=await db.from('players').select('*').order('wins',{ascending:false}).order('games_played',{ascending:false});if(error)throw error;c.innerHTML=`<section class="panel"><div class="panel-head"><h3>CHAMPIONS OF THE WAR</h3></div><div class="table">${(data||[]).map((p,i)=>`<div class="rank-row"><b>#${i+1}</b><strong>${esc(p.display_name)}</strong><span>${esc(p.primary_faction||'Unassigned')}</span><strong>${p.wins||0}W / ${p.losses||0}L / ${p.draws||0}D</strong><em>${rate(p)}%</em></div>`).join('')||'<div class="empty">No ranked players yet.</div>'}</div></section>`}
async function factions(c){const {data,error}=await db.from('players').select('primary_faction');if(error)throw error;const counts={};(data||[]).forEach(p=>{if(p.primary_faction)counts[p.primary_faction]=(counts[p.primary_faction]||0)+1});c.innerHTML=`<section class="panel"><div class="panel-head"><h3>FACTION ARCHIVES</h3></div><div class="faction-grid">${FACTIONS.map(f=>`<article><span>⚔</span><h3>${f}</h3><b>${counts[f]||0} registered</b></article>`).join('')}</div></section>`}
async function groups(c){const {data,error}=await db.from('groups').select('*').order('created_at',{ascending:false});if(error)throw error;c.innerHTML=`<section class="panel"><div class="panel-head"><h3>BATTLE GROUPS</h3><div><button class="secondary" id="joinGroup">JOIN</button> <button class="primary" id="createGroup">CREATE</button></div></div><div class="group-grid">${(data||[]).map(g=>`<article class="group-card"><h3>${esc(g.name)}</h3><span>INVITE CODE: <strong>${esc(g.invite_code)}</strong></span></article>`).join('')||'<div class="empty">No battle groups found.</div>'}</div></section>`;$('#createGroup').onclick=openGroupCreate;$('#joinGroup').onclick=openGroupJoin}
async function matches(c){const {data,error}=await db.from('matches').select('*').eq('player_user_id',S.user.id).order('created_at',{ascending:false}).limit(30);if(error)throw error;c.innerHTML=`<section class="panel"><div class="panel-head"><h3>MATCH REGISTER</h3></div>${(data||[]).map(m=>`<div class="game-row"><div><strong>MATCH ${esc(m.id.slice(0,8))}</strong><span>${date(m.created_at)}</span></div><b>${esc(m.status)}</b></div>`).join('')||'<div class="empty">No matches registered.</div>'}</section>`}
async function profile(c){await loadFactions();c.innerHTML=`<section class="profile-dossier"><div class="profile-hero">${avatar(S.profile,'profile-avatar')}<div><div class="eyebrow">PERSONNEL DOSSIER</div><h2>${esc(S.profile.display_name)}</h2><p>${esc(S.profile.bio||'No battle oath recorded.')}</p></div></div><section class="stats profile-stats"><article><small>WINS</small><b>${S.player.wins||0}</b></article><article><small>LOSSES</small><b>${S.player.losses||0}</b></article><article><small>DRAWS</small><b>${S.player.draws||0}</b></article><article class="rate"><small>WIN RATE</small><b>${rate(S.player)}%</b></article></section><div class="panel"><div class="panel-head"><h3>EDIT DOSSIER</h3></div><form id="profileForm" class="form-grid"><label>CALLSIGN<input id="pName" value="${esc(S.profile.display_name)}" required></label><label>PRIMARY FACTION<select id="pFaction"><option value="">Unassigned</option>${FACTIONS.map(f=>`<option ${S.player.primary_faction===f?'selected':''}>${f}</option>`).join('')}</select></label><label class="wide">BIO<textarea id="pBio">${esc(S.profile.bio||'')}</textarea></label><label class="wide">PROFILE ICON<input id="avatarFile" type="file" accept="image/png,image/jpeg,image/webp"><small class="field-help">Upload PNG, JPG or WEBP up to 1 MB.</small></label><div class="wide"><button class="primary">SAVE DOSSIER</button></div></form></div><div class="panel"><div class="panel-head"><h3>FACTION ROSTER</h3><button class="secondary" id="addFaction">+ ADD FACTION</button></div><div class="faction-roster">${S.factions.length?S.factions.map(f=>`<span class="faction-chip">${esc(f)} <button data-remove-faction="${esc(f)}">×</button></span>`).join(''):'<div class="empty">Add the armies you command.</div>'}</div></div></section>`;$('#profileForm').onsubmit=saveProfile;$('#addFaction').onclick=openFactionAdd;document.querySelectorAll('[data-remove-faction]').forEach(b=>b.onclick=()=>removeFaction(b.dataset.removeFaction))}
async function saveProfile(e){e.preventDefault();const name=$('#pName').value.trim(),faction=$('#pFaction').value||null,bio=$('#pBio').value.trim()||null;notice('SAVING DOSSIER…');let avatarUrl=S.profile.avatar_url||null;const file=$('#avatarFile').files[0];if(file){if(file.size>1048576)return notice('PROFILE ICON MUST BE 1 MB OR SMALLER.','error');avatarUrl=await imageData(file)}const a=await db.from('profiles').update({display_name:name,bio,avatar_url:avatarUrl,updated_at:new Date().toISOString()}).eq('id',S.user.id);if(a.error)return notice(a.error.message,'error');const b=await db.from('players').update({display_name:name,primary_faction:faction,updated_at:new Date().toISOString()}).eq('user_id',S.user.id);if(b.error)return notice(b.error.message,'error');S.profile={...S.profile,display_name:name,bio,avatar_url:avatarUrl};S.player={...S.player,display_name:name,primary_faction:faction};notice('DOSSIER UPDATED.','success');setTimeout(async()=>{renderShell();await renderView()},400)}
function imageData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=512,scale=Math.min(1,max/Math.max(im.width,im.height)),cv=document.createElement('canvas');cv.width=Math.max(1,Math.round(im.width*scale));cv.height=Math.max(1,Math.round(im.height*scale));cv.getContext('2d').drawImage(im,0,0,cv.width,cv.height);resolve(cv.toDataURL('image/webp',.82))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function openFactionAdd(){const options=FACTIONS.filter(f=>!S.factions.includes(f)).map(f=>`<option>${f}</option>`).join('');openModal(`<div class="panel-head"><h3>ADD ARMY TO ROSTER</h3><button class="secondary" id="closeModal">CLOSE</button></div><form id="factionForm"><label>FACTION<select id="newFaction">${options||'<option>No factions remaining</option>'}</select></label><button class="primary">ADD TO ROSTER</button></form>`);$('#closeModal').onclick=closeModal;$('#factionForm').onsubmit=async e=>{e.preventDefault();const faction=$('#newFaction').value;if(!faction)return;const {error}=await db.from('player_factions').insert({player_id:S.player.id,faction});if(error)return notice(error.message,'error');closeModal();await renderView()}}
async function removeFaction(f){const {error}=await db.from('player_factions').delete().eq('player_id',S.player.id).eq('faction',f);if(error)return notice(error.message,'error');await renderView()}
function openModal(html){const m=$('#modal');m.hidden=false;m.innerHTML=`<div class="modal-card">${html}</div>`} function closeModal(){const m=$('#modal');m.hidden=true;m.innerHTML=''}
function openBattle(){const choices=[S.player.primary_faction,...S.factions].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i);openModal(`<div class="panel-head"><h3>RECORD BATTLE</h3><button class="secondary" id="closeModal">CLOSE</button></div><form id="battleForm" class="form-grid"><label>OPPONENT<input id="opponent" required></label><label>RESULT<select id="result"><option value="win">VICTORY</option><option value="loss">DEFEAT</option><option value="draw">DRAW</option></select></label><label>YOUR FACTION<select id="yourFaction">${choices.map(f=>`<option>${esc(f)}</option>`).join('')||FACTIONS.map(f=>`<option>${f}</option>`).join('')}</select></label><label>OPPONENT FACTION<select id="oppFaction"><option value="">Unknown</option>${FACTIONS.map(f=>`<option>${f}</option>`).join('')}</select></label><label>YOUR VP<input id="yourVp" type="number" min="0"></label><label>OPPONENT VP<input id="oppVp" type="number" min="0"></label><label>MISSION<input id="mission"></label><label class="wide">NOTES<textarea id="notes"></textarea></label><div class="wide"><button class="primary">SAVE BATTLE REPORT</button></div></form>`);$('#closeModal').onclick=closeModal;$('#battleForm').onsubmit=saveBattle}
async function saveBattle(e){e.preventDefault();const result=$('#result').value;const row={owner_user_id:S.user.id,opponent_name:$('#opponent').value.trim(),player_faction:$('#yourFaction').value,opponent_faction:$('#oppFaction').value||null,result,player_score:$('#yourVp').value?Number($('#yourVp').value):null,opponent_score:$('#oppVp').value?Number($('#oppVp').value):null,mission:$('#mission').value.trim()||null,notes:$('#notes').value.trim()||null,played_at:new Date().toISOString()};const {error}=await db.from('games').insert(row);if(error)return notice(error.message,'error');const next={games_played:(S.player.games_played||0)+1,wins:(S.player.wins||0)+(result==='win'?1:0),losses:(S.player.losses||0)+(result==='loss'?1:0),draws:(S.player.draws||0)+(result==='draw'?1:0),updated_at:new Date().toISOString()};const u=await db.from('players').update(next).eq('user_id',S.user.id);if(u.error)return notice(u.error.message,'error');Object.assign(S.player,next);closeModal();notice('BATTLE REPORT ARCHIVED.','success');await renderView()}
function openGroupCreate(){openModal(`<div class="panel-head"><h3>CREATE BATTLE GROUP</h3><button class="secondary" id="closeModal">CLOSE</button></div><form id="groupForm"><label>GROUP NAME<input id="groupName" maxlength="60" required></label><button class="primary">CREATE GROUP</button></form>`);$('#closeModal').onclick=closeModal;$('#groupForm').onsubmit=async e=>{e.preventDefault();const name=$('#groupName').value.trim(),code=Math.random().toString(36).slice(2,8).toUpperCase();const {error}=await db.from('groups').insert({name,invite_code:code,owner_user_id:S.user.id});if(error)return notice(error.message,'error');closeModal();await renderView()}}
function openGroupJoin(){openModal(`<div class="panel-head"><h3>JOIN BATTLE GROUP</h3><button class="secondary" id="closeModal">CLOSE</button></div><form id="joinForm"><label>INVITE CODE<input id="invite" maxlength="12" required></label><button class="primary">JOIN GROUP</button></form>`);$('#closeModal').onclick=closeModal;$('#joinForm').onsubmit=async e=>{e.preventDefault();const code=$('#invite').value.trim().toUpperCase();const {data,error}=await db.from('groups').select('id').eq('invite_code',code).maybeSingle();if(error||!data)return notice(error?.message||'GROUP NOT FOUND.','error');const r=await db.from('group_members').insert({group_id:data.id,user_id:S.user.id});if(r.error)return notice(r.error.message,'error');closeModal();await renderView()}}
init();
