const SUPABASE_URL='https://jbgwdxavydhtvoqpbfmj.supabase.co';
const SUPABASE_KEY='sb_publishable_Wt8h6fNelT6zrzf-Dm8FXw_cdSGylaz';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);

const $=(s)=>document.querySelector(s);
const appState={user:null,profile:null,player:null,view:'dashboard'};

function escapeHtml(v=''){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
function notice(msg,type='info'){const el=$('#notice');if(el){el.textContent=msg;el.className=`notice ${type}`;}}
function show(view){appState.view=view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));renderView();}

async function signIn(e){e?.preventDefault();const email=$('#loginEmail')?.value.trim();const password=$('#loginPassword')?.value;if(!email||!password)return notice('Enter your email and password.','error');notice('CONNECTING…');const {data,error}=await db.auth.signInWithPassword({email,password});if(error)return notice(error.message,'error');await boot(data.user);}
async function signUp(e){e?.preventDefault();const email=$('#signupEmail')?.value.trim();const password=$('#signupPassword')?.value;const name=$('#signupName')?.value.trim();if(!email||!password||!name)return notice('Complete all fields.','error');if(password.length<6)return notice('Password must be at least 6 characters.','error');notice('CREATING PLAYER…');const {data,error}=await db.auth.signUp({email,password,options:{data:{display_name:name}}});if(error)return notice(error.message,'error');if(data.session) await boot(data.user); else notice('Account created. Check your email if confirmation is enabled.','success');}
async function signOut(){await db.auth.signOut();appState.user=null;appState.profile=null;appState.player=null;renderLogin();}

async function boot(user){appState.user=user;const [p,pl]=await Promise.all([db.from('profiles').select('*').eq('id',user.id).maybeSingle(),db.from('players').select('*').eq('user_id',user.id).maybeSingle()]);appState.profile=p.data;appState.player=pl.data;if(!appState.profile){const name=user.user_metadata?.display_name||user.email.split('@')[0];const r=await db.from('profiles').upsert({id:user.id,display_name:name}).select().single();appState.profile=r.data;}if(!appState.player){const name=appState.profile?.display_name||user.email.split('@')[0];const r=await db.from('players').upsert({user_id:user.id,display_name:name}).select().single();appState.player=r.data;}renderApp();}

function renderLogin(){document.body.innerHTML=`<main class="login-shell"><div class="login-card"><div class="sigil">⚔</div><div class="eyebrow">IMPERIAL WAR RECORDS</div><h1>ROUTINE <span>721</span></h1><p class="muted">BATTLE COMMAND TERMINAL</p><div class="tabs"><button id="loginTab" class="active">SIGN IN</button><button id="signupTab">CREATE PLAYER</button></div><form id="loginForm"><label>EMAIL<input id="loginEmail" type="email" autocomplete="email" required></label><label>PASSWORD<input id="loginPassword" type="password" autocomplete="current-password" required></label><button class="primary" type="submit">ENTER THE WAR ROOM</button></form><form id="signupForm" hidden><label>CALLSIGN<input id="signupName" required maxlength="40"></label><label>EMAIL<input id="signupEmail" type="email" autocomplete="email" required></label><label>PASSWORD<input id="signupPassword" type="password" autocomplete="new-password" minlength="6" required></label><button class="primary" type="submit">CREATE PLAYER</button></form><div id="notice" class="notice"></div></div></main>`;$('#loginForm').onsubmit=signIn;$('#signupForm').onsubmit=signUp;$('#loginTab').onclick=()=>{$('#loginForm').hidden=false;$('#signupForm').hidden=true;$('#loginTab').classList.add('active');$('#signupTab').classList.remove('active');};$('#signupTab').onclick=()=>{$('#loginForm').hidden=true;$('#signupForm').hidden=false;$('#signupTab').classList.add('active');$('#loginTab').classList.remove('active');};}

async function renderView(){const c=$('#page');if(!c)return;const title={dashboard:'WAR ROOM',players:'PLAYERS',leaderboard:'LEADERBOARD',factions:'FACTIONS',groups:'BATTLE GROUPS',matches:'MATCHES',profile:'MY PROFILE'}[appState.view]||'WAR ROOM';$('#pageTitle').textContent=title;if(appState.view==='dashboard')return dashboard(c);if(appState.view==='players')return players(c);if(appState.view==='leaderboard')return leaderboard(c);if(appState.view==='factions')return factions(c);if(appState.view==='groups')return groups(c);if(appState.view==='matches')return matches(c);if(appState.view==='profile')return profile(c);}
async function dashboard(c){const {data:games}=await db.from('games').select('*').eq('owner_user_id',appState.user.id).order('played_at',{ascending:false}).limit(8);const g=games||[];const wins=g.filter(x=>x.result==='win').length;const losses=g.filter(x=>x.result==='loss').length;c.innerHTML=`<section class="hero"><div><div class="eyebrow">TACTICAL COMMAND</div><h2>Welcome, ${escapeHtml(appState.profile.display_name)}</h2><p>Record the battles. Track the victories. Build your legend.</p></div><button class="primary" id="newGame">+ RECORD BATTLE</button></section><section class="stats"><article><small>BATTLES</small><b>${g.length}</b></article><article><small>VICTORIES</small><b>${wins}</b></article><article><small>DEFEATS</small><b>${losses}</b></article><article><small>WIN RATE</small><b>${g.length?Math.round(wins/g.length*100):0}%</b></article></section><section class="panel"><div class="panel-head"><h3>RECENT BATTLES</h3></div>${g.length?g.map(gameRow).join(''):'<div class="empty">No battle records yet. Your first campaign awaits.</div>'}</section>`;$('#newGame').onclick=()=>openGameForm();}
function gameRow(x){return `<div class="game-row"><div><strong>${escapeHtml(x.opponent_name)}</strong><span>${escapeHtml(x.player_faction||'Unrecorded faction')} · ${new Date(x.played_at).toLocaleDateString()}</span></div><b class="result ${x.result}">${x.result.toUpperCase()}</b></div>`;}
async function players(c){const {data}=await db.from('players').select('*').order('wins',{ascending:false});c.innerHTML=`<section class="panel"><div class="panel-head"><h3>PLAYERS</h3></div><div class="player-grid">${(data||[]).map(p=>`<article class="player-card"><div class="avatar">${escapeHtml((p.display_name||'?')[0].toUpperCase())}</div><h3>${escapeHtml(p.display_name)}</h3><p>${escapeHtml(p.primary_faction||'No faction declared')}</p><div class="player-stats"><span>${p.games_played} GAMES</span><strong>${p.wins} WINS</strong></div></article>`).join('')}</div></section>`;}
async function leaderboard(c){const {data}=await db.from('players').select('*').order('wins',{ascending:false}).order('games_played',{ascending:true});c.innerHTML=`<section class="panel"><div class="panel-head"><h3>LEADERBOARD</h3></div><div class="table">${(data||[]).map((p,i)=>`<div class="rank-row"><b>#${i+1}</b><span>${escapeHtml(p.display_name)}</span><span>${p.wins}W / ${p.losses}L</span><strong>${p.games_played?Math.round(p.wins/p.games_played*100):0}%</strong></div>`).join('')}</div></section>`;}
async function factions(c){const {data}=await db.from('players').select('primary_faction');const counts={};(data||[]).forEach(p=>{if(p.primary_faction)counts[p.primary_faction]=(counts[p.primary_faction]||0)+1});c.innerHTML=`<section class="panel"><div class="panel-head"><h3>FACTION REGISTRY</h3></div><div class="faction-grid">${Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([f,n])=>`<article><span>⚔</span><h3>${escapeHtml(f)}</h3><b>${n} PLAYER${n===1?'':'S'}</b></article>`).join('')||'<div class="empty">No factions registered yet.</div>'}</div></section>`;}
async function groups(c){const {data}=await db.from('groups').select('*').order('created_at',{ascending:false});c.innerHTML=`<section class="panel"><div class="panel-head"><h3>BATTLE GROUPS</h3><button class="secondary" id="newGroup">CREATE GROUP</button></div><div class="group-grid">${(data||[]).map(g=>`<article class="group-card"><h3>${escapeHtml(g.name)}</h3><span>INVITE CODE: ${escapeHtml(g.invite_code)}</span></article>`).join('')||'<div class="empty">No battle groups yet.</div>'}</div></section>`;$('#newGroup').onclick=createGroup;}
async function createGroup(){const name=prompt('Battle group name');if(!name)return;const code=Math.random().toString(36).slice(2,8).toUpperCase();const {error}=await db.from('groups').insert({name,invite_code:code,owner_user_id:appState.user.id});if(error)return alert(error.message);await db.from('group_members').insert({group_id:(await db.from('groups').select('id').eq('invite_code',code).single()).data.id,user_id:appState.user.id,role:'owner'});renderView();}
async function matches(c){const {data}=await db.from('matches').select('*').eq('player_user_id',appState.user.id).order('created_at',{ascending:false});c.innerHTML=`<section class="panel"><div class="panel-head"><h3>MATCHES</h3></div>${(data||[]).map(m=>`<div class="game-row"><span>${m.status.toUpperCase()}</span><small>${new Date(m.created_at).toLocaleString()}</small></div>`).join('')||'<div class="empty">No matches recorded.</div>'}</section>`;}
async function profile(c){const p=appState.profile,pl=appState.player;c.innerHTML=`<section class="panel"><div class="panel-head"><h3>MY PROFILE</h3></div><form id="profileForm" class="form-grid"><label>CALLSIGN<input id="profileName" value="${escapeHtml(p.display_name)}" required></label><label>PRIMARY FACTION<input id="profileFaction" value="${escapeHtml(pl.primary_faction||'')}" placeholder="e.g. Space Marines"></label><label class="wide">BIO<textarea id="profileBio">${escapeHtml(p.bio||'')}</textarea></label><button class="primary" type="submit">SAVE PROFILE</button></form></section>`;$('#profileForm').onsubmit=async e=>{e.preventDefault();const name=$('#profileName').value.trim(),faction=$('#profileFaction').value.trim(),bio=$('#profileBio').value.trim();const a=await db.from('profiles').update({display_name:name,bio,updated_at:new Date().toISOString()}).eq('id',appState.user.id);const b=await db.from('players').update({display_name:name,primary_faction:faction,updated_at:new Date().toISOString()}).eq('user_id',appState.user.id);if(a.error||b.error)return alert(a.error?.message||b.error?.message);await boot(appState.user);show('profile');};}
function openGameForm(){const c=$('#modal');c.innerHTML=`<div class="modal-card"><div class="panel-head"><h3>RECORD BATTLE</h3><button id="closeModal">×</button></div><form id="gameForm" class="form-grid"><label>OPPONENT<input id="opponent" required></label><label>OPPONENT FACTION<input id="oppFaction"></label><label>YOUR FACTION<input id="yourFaction" value="${escapeHtml(appState.player.primary_faction||'')}"></label><label>RESULT<select id="result"><option value="win">VICTORY</option><option value="loss">DEFEAT</option><option value="draw">DRAW</option></select></label><label>SCORE<input id="score" type="number"></label><label>MISSION<input id="mission"></label><label class="wide">NOTES<textarea id="notes"></textarea></label><button class="primary" type="submit">LOG BATTLE</button></form></div>`;c.hidden=false;$('#closeModal').onclick=()=>c.hidden=true;$('#gameForm').onsubmit=async e=>{e.preventDefault();const result=$('#result').value;const {error}=await db.from('games').insert({owner_user_id:appState.user.id,opponent_name:$('#opponent').value.trim(),opponent_faction:$('#oppFaction').value.trim(),player_faction:$('#yourFaction').value.trim(),result,player_score:Number($('#score').value)||null,mission:$('#mission').value.trim(),notes:$('#notes').value.trim()});if(error)return alert(error.message);const delta=result==='win'?{games_played:appState.player.games_played+1,wins:appState.player.wins+1}:result==='loss'?{games_played:appState.player.games_played+1,losses:appState.player.losses+1}:{games_played:appState.player.games_played+1};await db.from('players').update(delta).eq('user_id',appState.user.id);c.hidden=true;renderView();};}
function renderApp(){document.body.innerHTML=`<div id="app"><header class="topbar"><div><div class="brand">ROUTINE 721</div><div class="brand-sub">IMPERIAL BATTLE COMMAND</div></div><div class="user-area"><span>${escapeHtml(appState.profile.display_name)}</span><button id="logout" class="secondary">SIGN OUT</button></div></header><div class="layout"><aside class="sidebar"><div class="sidebar-label">COMMAND DECK</div>${[['dashboard','WAR ROOM'],['players','PLAYERS'],['leaderboard','LEADERBOARD'],['factions','FACTIONS'],['groups','BATTLE GROUPS'],['matches','MATCHES'],['profile','MY PROFILE']].map(([id,n])=>`<button data-view="${id}" class="nav-button">${n}</button>`).join('')}</aside><main class="content"><div class="content-title"><div><div class="eyebrow">ACTIVE CAMPAIGN</div><h1 id="pageTitle"></h1></div><div id="notice"></div></div><div id="page"></div></main></div></div><div id="modal" hidden></div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#logout').onclick=signOut;show('dashboard');}

db.auth.onAuthStateChange((event,session)=>{if(session?.user&&!appState.user)boot(session.user);else if(event==='SIGNED_OUT')renderLogin();});
(async()=>{const {data}=await db.auth.getSession();if(data.session)await boot(data.session.user);else renderLogin();})();