const SUPABASE_URL='https://jbgwdxavydhtvoqpbfmj.supabase.co';
const SUPABASE_KEY='sb_publishable_Wt8h6fNelT6zrzf-Dm8FXw_cdSGylaz';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const S={user:null,profile:null,player:null,view:'dashboard'};
const factions=['Space Marines','Astra Militarum','Adeptus Mechanicus','Adeptus Custodes','Grey Knights','Sisters of Battle','Necrons','Aeldari','Drukhari','Orks','Tyranids','Genestealer Cults','Chaos Space Marines','Death Guard','Thousand Sons','World Eaters','Chaos Daemons','Leagues of Votann','T’au Empire'];
const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function msg(t,type=''){const n=$('#notice');if(n){n.textContent=t;n.className='notice '+type}}
function fmt(d){return d?new Date(d).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—'}
function initials(n){return (n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
async function signIn(e){e.preventDefault();msg('CONNECTING…');const {data,error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error)return msg(error.message,'error');await boot(data.user)}
async function signUp(e){e.preventDefault();msg('CREATING PLAYER…');const name=$('#signupName').value.trim(),email=$('#signupEmail').value.trim(),password=$('#signupPassword').value;if(password.length<6)return msg('Password must be at least 6 characters.','error');const {data,error}=await db.auth.signUp({email,password,options:{data:{display_name:name}}});if(error)return msg(error.message,'error');if(data.session)await boot(data.user);else msg('Account created. Check your email if confirmation is enabled.','success')}
function login(){document.body.innerHTML=`<main class="login-shell"><section class="login-card"><div class="sigil">⚔</div><div class="eyebrow">IMPERIAL WAR RECORDS</div><h1>ROUTINE <span>721</span></h1><p class="muted">BATTLE COMMAND TERMINAL</p><div class="tabs"><button id="lt" class="active">SIGN IN</button><button id="st">CREATE PLAYER</button></div><form id="lf"><label>EMAIL<input id="loginEmail" type="email" autocomplete="email" required></label><label>PASSWORD<input id="loginPassword" type="password" autocomplete="current-password" required></label><button class="primary" type="submit">ENTER THE WAR ROOM</button></form><form id="sf" hidden><label>CALLSIGN<input id="signupName" maxlength="40" required></label><label>EMAIL<input id="signupEmail" type="email" autocomplete="email" required></label><label>PASSWORD<input id="signupPassword" type="password" minlength="6" autocomplete="new-password" required></label><button class="primary" type="submit">CREATE PLAYER</button></form><div id="notice" class="notice"></div></section></main>`;$('#lf').onsubmit=signIn;$('#sf').onsubmit=signUp;$('#lt').onclick=()=>{$('#lf').hidden=false;$('#sf').hidden=true;$('#lt').classList.add('active');$('#st').classList.remove('active')};$('#st').onclick=()=>{$('#lf').hidden=true;$('#sf').hidden=false;$('#st').classList.add('active');$('#lt').classList.remove('active')}}
async function boot(user){S.user=user;let p=(await db.from('profiles').select('*').eq('id',user.id).maybeSingle()).data;if(!p){const name=user.user_metadata?.display_name||user.email.split('@')[0];const r=await db.from('profiles').insert({id:user.id,display_name:name}).select().single();if(r.error)return loginError(r.error);p=r.data}S.profile=p;let pl=(await db.from('players').select('*').eq('user_id',user.id).maybeSingle()).data;if(!pl){const r=await db.from('players').insert({user_id:user.id,display_name:p.display_name}).select().single();if(r.error)return loginError(r.error);pl=r.data}S.player=pl;renderShell();await renderView()}
function loginError(e){document.body.innerHTML=`<main class="login-shell"><section class="login-card"><div class="sigil">⚠</div><h1>COMMAND ERROR</h1><p class="muted">${esc(e.message)}</p><button class="primary" onclick="login()">RETURN TO LOGIN</button></section></main>`}
function shell(){return `<header class="topbar"><div><div class="brand">ROUTINE 721</div><div class="brand-sub">IMPERIAL BATTLE COMMAND</div></div><div class="user-area"><span>${esc(S.profile.display_name)}</span><button id="logout" class="secondary">SIGN OUT</button></div></header><div class="layout"><aside class="sidebar"><div class="sidebar-label">COMMAND DECK</div>${[['dashboard','WAR ROOM','⌂'],['players','PLAYERS','♙'],['leaderboard','LEADERBOARD','♛'],['factions','FACTIONS','⚔'],['groups','BATTLE GROUPS','✦'],['matches','MATCHES','◈'],['profile','MY PROFILE','◎']].map(x=>`<button class="nav-button" data-view="${x[0]}"><i>${x[2]}</i>${x[1]}</button>`).join('')}</aside><main class="content"><div class="content-title"><div><div class="eyebrow">ACTIVE CAMPAIGN</div><h1 id="pageTitle"></h1></div><div id="notice"></div></div><div id="page"></div></main></div><div id="modal" hidden></div>`}
function renderShell(){document.body.innerHTML=`<div id="app">${shell()}</div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;renderView()});$('#logout').onclick=async()=>{await db.auth.signOut();S.user=null;login()}}
async function renderView(){const titles={dashboard:'WAR ROOM',players:'PLAYERS',leaderboard:'LEADERBOARD',factions:'FACTIONS',groups:'BATTLE GROUPS',matches:'MATCHES',profile:'MY PROFILE'};$('#pageTitle').textContent=titles[S.view];document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===S.view));({dashboard,players,leaderboard,factions,groups,matches,profile}[S.view]||dashboard)($('#page'))}
async function dashboard(c){const {data:g,error}=await db.from('games').select('*').eq('owner_user_id',S.user.id).order('played_at',{ascending:false}).limit(10);if(error)return c.innerHTML=err(error);const a=g||[],w=a.filter(x=>x.result==='win').length,l=a.filter(x=>x.result==='loss').length;c.innerHTML=`<section class="hero"><div><div class="eyebrow">TACTICAL COMMAND</div><h2>WELCOME, ${esc(S.profile.display_name).toUpperCase()}</h2><p>Your campaign record is ready for deployment.</p></div><button class="primary" id="record">+ RECORD BATTLE</button></section><section class="stats"><article><small>BATTLES</small><b>${S.player.games_played}</b></article><article><small>VICTORIES</small><b>${S.player.wins}</b></article><article><small>DEFEATS</small><b>${S.player.losses}</b></article><article><small>WIN RATE</small><b>${S.player.games_played?Math.round(S.player.wins/S.player.games_played*100):0}%</b></article></section><section class="panel"><div class="panel-head"><h3>RECENT BATTLE REPORTS</h3><button class="secondary" id="record2">LOG BATTLE</button></div>${a.length?a.map(game).join(''):'<div class="empty">No battles recorded. The first engagement awaits.</div>'}</section>`;$('#record').onclick=openGame;$('#record2').onclick=openGame}
function game(x){return `<div class="game-row"><div><strong>${esc(x.opponent_name)}</strong><span>${esc(x.player_faction||'Unknown')} vs ${esc(x.opponent_faction||'Unknown')} · ${fmt(x.played_at)}</span></div><div><b class="result ${x.result}">${x.result.toUpperCase()}</b><span>${x.player_score??'—'} VP</span></div></div>`}
async function players(c){const {data,error}=await db.from('players').select('*').order('wins',{ascending:false}).order('display_name');if(error)return c.innerHTML=err(error);c.innerHTML=`<section class="panel"><div class="panel-head"><h3>IMPERIAL PERSONNEL REGISTER</h3><button class="secondary" onclick="S.view='profile';renderView()">EDIT MY PROFILE</button></div><div class="player-grid">${(data||[]).map(p=>`<article class="player-card"><div class="avatar">${initials(p.display_name)}</div><h3>${esc(p.display_name)}</h3><p>${esc(p.primary_faction||'Faction unassigned')}</p><div class="player-stats"><span>${p.games_played} GAMES</span><strong>${p.wins}W / ${p.losses}L</strong></div></article>`).join('')}</div></section>`}
async function leaderboard(c){const {data,error}=await db.from('players').select('*').order('wins',{ascending:false}).order('games_played',{ascending:false});if(error)return c.innerHTML=err(error);c.innerHTML=`<section class="panel"><div class="panel-head"><h3>CHAPTER RANKINGS</h3></div><div class="table">${(data||[]).map((p,i)=>`<div class="rank-row"><b>#${i+1}</b><strong>${esc(p.display_name)}</strong><span>${p.wins}W · ${p.losses}L</span><em>${p.games_played?Math.round(p.wins/p.games_played*100):0}%</em></div>`).join('')||'<div class="empty">No ranked players yet.</div>'}</div></section>`}
async function factions(c){const {data,error}=await db.from('players').select('primary_faction');if(error)return c.innerHTML=err(error);const count={};(data||[]).forEach(p=>{if(p.primary_faction)count[p.primary_faction]=(count[p.primary_faction]||0)+1});c.innerHTML=`<section class="panel"><div class="panel-head"><h3>FACTION REGISTRY</h3></div><div class="faction-grid">${factions.map(f=>`<article><span>⚔</span><h3>${f}</h3><b>${count[f]||0} REGISTERED</b></article>`).join('')}</div></section>`}
async function groups(c){const {data,error}=await db.from('groups').select('*').order('created_at',{ascending:false});if(error)return c.innerHTML=err(error);c.innerHTML=`<section class="panel"><div class="panel-head"><h3>BATTLE GROUPS</h3><div class="actions"><button class="secondary" id="join">JOIN GROUP</button><button class="primary" id="newg">CREATE GROUP</button></div></div><div class="group-grid">${(data||[]).map(g=>`<article class="group-card"><div class="badge">✦</div><h3>${esc(g.name)}</h3><span>INVITE CODE · ${esc(g.invite_code)}</span><small>Commanded by ${g.owner_user_id===S.user.id?'YOU':'ANOTHER COMMANDER'}</small></article>`).join('')||'<div class="empty">No battle groups have been established.</div>'}</div></section>`;$('#newg').onclick=createGroup;$('#join').onclick=joinGroup}
async function createGroup(){const name=prompt('Battle group name');if(!name?.trim())return;const code=Math.random().toString(36).slice(2,8).toUpperCase();const r=await db.from('groups').insert({name:name.trim(),invite_code:code,owner_user_id:S.user.id}).select().single();if(r.error)return alert(r.error.message);const m=await db.from('group_members').insert({group_id:r.data.id,user_id:S.user.id,role:'owner'});if(m.error)return alert(m.error.message);renderView()}
async function joinGroup(){const code=prompt('Enter invite code');if(!code)return;const r=await db.from('groups').select('id').eq('invite_code',code.trim().toUpperCase()).maybeSingle();if(r.error||!r.data)return alert('Invite code not found.');const m=await db.from('group_members').insert({group_id:r.data.id,user_id:S.user.id,role:'member'});if(m.error)return alert(m.error.message);alert('Joined battle group.');renderView()}
async function matches(c){const {data,error}=await db.from('matches').select('*').eq('player_user_id',S.user.id).order('created_at',{ascending:false});if(error)return c.innerHTML=err(error);c.innerHTML=`<section class="panel"><div class="panel-head"><h3>OPEN MATCH REGISTER</h3></div>${(data||[]).map(m=>`<div class="game-row"><div><strong>${esc(m.status)}</strong><span>${fmt(m.created_at)}</span></div></div>`).join('')||'<div class="empty">No open matches.</div>'}</section>`}
async function profile(c){const p=S.profile,pl=S.player;c.innerHTML=`<section class="panel"><div class="profile-head"><div class="avatar big">${initials(p.display_name)}</div><div><div class="eyebrow">COMMANDER PROFILE</div><h2>${esc(p.display_name)}</h2><p>${esc(pl.primary_faction||'Faction unassigned')}</p></div></div><form id="pf" class="form-grid"><label>CALLSIGN<input id="pn" value="${esc(p.display_name)}" required></label><label>PRIMARY FACTION<select id="pfac"><option value="">Select faction</option>${factions.map(f=>`<option ${f===pl.primary_faction?'selected':''}>${f}</option>`).join('')}</select></label><label class="wide">BIO<textarea id="bio">${esc(p.bio||'')}</textarea></label><button class="primary" type="submit">SAVE PROFILE</button></form></section>`;$('#pf').onsubmit=async e=>{e.preventDefault();const name=$('#pn').value.trim(),fac=$('#pfac').value,bio=$('#bio').value.trim();const a=await db.from('profiles').update({display_name:name,bio,updated_at:new Date().toISOString()}).eq('id',S.user.id);const b=await db.from('players').update({display_name:name,primary_faction:fac||null,updated_at:new Date().toISOString()}).eq('user_id',S.user.id);if(a.error||b.error)return alert(a.error?.message||b.error?.message);await boot(S.user)}}
function openGame(){const m=$('#modal');m.innerHTML=`<div class="modal-card"><div class="panel-head"><h3>RECORD BATTLE</h3><button id="close">×</button></div><form id="gf" class="form-grid"><label>OPPONENT CALLSIGN<input id="op" required></label><label>OPPONENT FACTION<input id="of"></label><label>YOUR FACTION<select id="yf">${factions.map(f=>`<option ${f===S.player.primary_faction?'selected':''}>${f}</option>`).join('')}</select></label><label>RESULT<select id="res"><option value="win">VICTORY</option><option value="loss">DEFEAT</option><option value="draw">DRAW</option></select></label><label>YOUR VP<input id="ps" type="number" min="0"></label><label>OPPONENT VP<input id="os" type="number" min="0"></label><label>MISSION<input id="mission"></label><label>DATE<input id="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label class="wide">BATTLE NOTES<textarea id="notes"></textarea></label><button class="primary" type="submit">CONFIRM BATTLE REPORT</button></form></div>`;m.hidden=false;$('#close').onclick=()=>m.hidden=true;$('#gf').onsubmit=async e=>{e.preventDefault();const result=$('#res').value;const g=await db.from('games').insert({owner_user_id:S.user.id,opponent_name:$('#op').value.trim(),opponent_faction:$('#of').value.trim()||null,player_faction:$('#yf').value, result,player_score:Number($('#ps').value)||null,opponent_score:Number($('#os').value)||null,mission:$('#mission').value.trim()||null,notes:$('#notes').value.trim()||null,played_at:new Date($('#date').value+'T12:00:00').toISOString()}).select().single();if(g.error)return alert(g.error.message);const delta={games_played:S.player.games_played+1,wins:S.player.wins+(result==='win'?1:0),losses:S.player.losses+(result==='loss'?1:0),updated_at:new Date().toISOString()};const u=await db.from('players').update(delta).eq('user_id',S.user.id);if(u.error)return alert(u.error.message);m.hidden=true;await boot(S.user)}}
function err(e){return `<div class="empty errorbox">${esc(e.message||'Unable to load records.')}</div>`}
db.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){S.user=null;login()} });
(async()=>{const {data}=await db.auth.getSession();if(data.session)await boot(data.session.user);else login()})();