const SUPABASE_URL='https://jbgwdxavydhtvoqpbfmj.supabase.co';
const SUPABASE_KEY='sb_publishable_Wt8h6fNelT6zrzf-Dm8FXw_cdSGylaz';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const FACTIONS=['Space Marines','Astra Militarum','Adeptus Mechanicus','Adeptus Custodes','Grey Knights','Sisters of Battle','Necrons','Aeldari','Drukhari','Orks','Tyranids','Genestealer Cults','Chaos Space Marines','Death Guard','Thousand Sons','World Eaters','Chaos Daemons','Leagues of Votann','T’au Empire'];
const S={user:null,profile:null,player:null,view:'dashboard'};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=n=>(String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?');
const date=d=>d?new Date(d).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—';
function notice(t,type=''){const n=$('#notice');if(n){n.textContent=t;n.className='notice '+type}}
function errorBox(e){return `<div class="empty"><strong>COMMAND ERROR</strong><br><span>${esc(e?.message||e)}</span></div>`}
function loading(){return `<div class="empty">LOADING COMMAND DATA…</div>`}

async function init(){
  try{const {data,error}=await db.auth.getSession();if(error)throw error;if(data.session)await enter(data.session.user);else showLogin();}
  catch(e){showLogin();setTimeout(()=>notice(e.message,'error'),0)}
  db.auth.onAuthStateChange(async(_event,session)=>{if(session&&!S.user)await enter(session.user);});
}
function showLogin(){
 document.body.innerHTML=`<main class="login-shell"><section class="login-card"><div class="sigil">⚔</div><div class="eyebrow">IMPERIAL WAR RECORDS</div><h1>ROUTINE <span>721</span></h1><p class="muted">BATTLE COMMAND TERMINAL</p><div class="tabs"><button id="signTab" class="active">SIGN IN</button><button id="createTab">CREATE PLAYER</button></div><form id="signForm"><label>EMAIL<input id="email" type="email" autocomplete="email" required></label><label>PASSWORD<input id="password" type="password" autocomplete="current-password" required></label><button class="primary" type="submit">ENTER THE WAR ROOM</button></form><form id="createForm" hidden><label>CALLSIGN<input id="callsign" maxlength="40" required></label><label>EMAIL<input id="newEmail" type="email" autocomplete="email" required></label><label>PASSWORD<input id="newPassword" type="password" minlength="6" autocomplete="new-password" required></label><button class="primary" type="submit">CREATE PLAYER</button></form><div id="notice" class="notice"></div></section></main>`;
 $('#signForm').onsubmit=async e=>{e.preventDefault();notice('CONNECTING…');const {data,error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)return notice(error.message,'error');await enter(data.user)};
 $('#createForm').onsubmit=async e=>{e.preventDefault();notice('CREATING PLAYER…');const name=$('#callsign').value.trim(),email=$('#newEmail').value.trim(),password=$('#newPassword').value;if(password.length<6)return notice('Password must be at least 6 characters.','error');const {data,error}=await db.auth.signUp({email,password,options:{data:{display_name:name}}});if(error)return notice(error.message,'error');if(data.session)await enter(data.user);else notice('Account created. Check your email if confirmation is enabled.','success')};
 $('#signTab').onclick=()=>{ $('#signForm').hidden=false;$('#createForm').hidden=true;$('#signTab').classList.add('active');$('#createTab').classList.remove('active')};
 $('#createTab').onclick=()=>{ $('#signForm').hidden=true;$('#createForm').hidden=false;$('#createTab').classList.add('active');$('#signTab').classList.remove('active')};
}
async function enter(user){
 S.user=user;
 let {data:p,error}=await db.from('profiles').select('*').eq('id',user.id).maybeSingle();
 if(error) return authFailure(error);
 if(!p){const name=user.user_metadata?.display_name||user.email.split('@')[0];const r=await db.from('profiles').insert({id:user.id,display_name:name}).select().single();if(r.error)return authFailure(r.error);p=r.data}
 S.profile=p;
 let {data:pl,error:pe}=await db.from('players').select('*').eq('user_id',user.id).maybeSingle();
 if(pe)return authFailure(pe);
 if(!pl){const r=await db.from('players').insert({user_id:user.id,display_name:p.display_name,primary_faction:null,games_played:0,wins:0,losses:0}).select().single();if(r.error)return authFailure(r.error);pl=r.data}
 S.player=pl;renderShell();await renderView();
}
function authFailure(e){S.user=null;showLogin();setTimeout(()=>notice(e.message,'error'),0)}
function renderShell(){
 document.body.innerHTML=`<div id="app"><header class="topbar"><div><div class="brand">ROUTINE 721</div><div class="brand-sub">IMPERIAL BATTLE COMMAND</div></div><div class="user-area"><span>${esc(S.profile.display_name)}</span><button id="logout" class="secondary">SIGN OUT</button></div></header><div class="layout"><aside class="sidebar"><div class="sidebar-label">COMMAND DECK</div>${nav('dashboard','WAR ROOM','⌂')}${nav('players','PLAYERS','♙')}${nav('leaderboard','LEADERBOARD','♛')}${nav('factions','FACTIONS','⚔')}${nav('groups','BATTLE GROUPS','✦')}${nav('matches','MATCHES','◈')}${nav('profile','MY PROFILE','◎')}</aside><main class="content"><div class="content-title"><div><div class="eyebrow">ACTIVE CAMPAIGN</div><h1 id="pageTitle"></h1></div><div id="notice"></div></div><div id="page"></div></main></div><div id="modal" hidden></div></div>`;
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;renderView()});$('#logout').onclick=async()=>{await db.auth.signOut();S.user=null;S.profile=null;S.player=null;showLogin()};
}
function nav(v,t,i){return `<button class="nav-button" data-view="${v}"><i>${i}</i> ${t}</button>`}
async function renderView(){const titles={dashboard:'WAR ROOM',players:'PLAYERS',leaderboard:'LEADERBOARD',factions:'FACTIONS',groups:'BATTLE GROUPS',matches:'MATCHES',profile:'MY PROFILE'};$('#pageTitle').textContent=titles[S.view];document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===S.view));const fn={dashboard,players,leaderboard,factions,groups,matches,profile}[S.view];$('#page').innerHTML=loading();try{await fn($('#page))}catch(e){$('#page').innerHTML=errorBox(e)}}
async function dashboard(c){const {data:g,error}=await db.from('games').select('*').eq('owner_user_id',S.user.id).order('played_at',{ascending:false}).limit(8);if(error)throw error;const a=g||[];c.innerHTML=`<section class="hero"><div><div class="eyebrow">TACTICAL COMMAND</div><h2>WELCOME, ${esc(S.profile.display_name).toUpperCase()}</h2><p>Your campaign record is ready for deployment.</p></div><button class="primary" id="recordBattle">+ RECORD BATTLE</button></section><section class="stats"><article><small>BATTLES</small><b>${S.player.games_played}</b></article><article><small>VICTORIES</small><b>${S.player.wins}</b></article><article><small>DEFEATS</small><b>${S.player.losses}</b></article><article><small>WIN RATE</small><b>${S.player.games_played?Math.round(S.player.wins/S.player.games_played*100):0}%</b></article></section><section class="panel"><div class="panel-head"><h3>RECENT BATTLE REPORTS</h3><button class="secondary" id="recordBattle2">LOG BATTLE</button></div>${a.length?a.map(gameRow).join(''):'<div class="empty">No battles recorded. The first engagement awaits.</div>'}</section>`;$('#recordBattle').onclick=openBattle;$('#recordBattle2').onclick=openBattle}
function gameRow(x){return `<div class="game-row"><div><strong>${esc(x.opponent_name)}</strong><span>${esc(x.player_faction||'Unknown')} vs ${esc(x.opponent_faction||'Unknown')} · ${date(x.played_at)}</span></div><div><b class="result ${esc(x.result)}">${esc(x.result).toUpperCase()}</b><span>${x.player_score??'—'} VP</span></div></div>`}
async function players(c){const {data,error}=await db.from('players').select('*').order('wins',{ascending:false}).order('display_name');if(error)throw error;c.innerHTML=`<section class="panel"><div class="panel-head"><h3>IMPERIAL PERSONNEL REGISTER</h3></div><div class="player-grid">${(data||[]).map(p=>`<article class="player-card"><div class="avatar">${initials(p.display_name)}</div><h3>${esc(p.display_name)}</h3><p>${esc(p.primary_faction||'Faction unassigned')}</p><div class="player-stats"><span>${p.games_played} GAMES</span><strong>${p.wins}W / ${p.losses}L</strong></div></article>`).join('')}</div></section>`}
async function leaderboard(c){const {data,error}=await db.from('players').select('*').order('wins',{ascending:false}).order('games_played',{ascending:false});if(error)throw error;c.innerHTML=`<section class="panel"><div class="panel-head"><h3>CHAMPIONS OF THE WAR</h3></div><div class="table">${(data||[]).map((p,i)=>`<div class="rank-row"><b>#${i+1}</b><strong>${esc(p.display_name)}</strong><span>${esc(p.primary_faction||'Unassigned')}</span><strong>${p.wins}W / ${p.losses}L</strong></div>`).join('')||'<div class="empty">No ranked players yet.</div>'}</div></section>`}
async function factions(c){const {data,error}=await db.from('players').select('primary_faction');if(error)throw error;const counts={};(data||[]).forEach(p=>{if(p.primary_faction)counts[p.primary_faction]=(counts[p.primary_faction]||0)+1});c.innerHTML=`<section class="panel"><div class="panel-head"><h3>FACTION ARCHIVES</h3></div><div class="faction-grid">${FACTIONS.map((f,i)=>`<article><span>⚔</span><h3>${f}</h3><b>${counts[f]||0} registered player${counts[f]===1?'':'s'}</b></article>`).join('')}</div></section>`}
async function groups(c){const {data,error}=await db.from('groups').select('*').order('created_at',{ascending:false});if(error)throw error;c.innerHTML=`<section class="panel"><div class="panel-head"><h3>BATTLE GROUPS</h3><div><button class="secondary" id="joinGroup">JOIN</button> <button class="primary" id="createGroup">CREATE</button></div></div><div class="group-grid">${(data||[]).map(g=>`<article class="group-card"><h3>${esc(g.name)}</h3><span>INVITE CODE: <strong>${esc(g.invite_code)}</strong></span></article>`).join('')||'<div class="empty">No battle groups found.</div>'}</div></section>`;$('#createGroup').onclick=openGroupCreate;$('#joinGroup').onclick=openGroupJoin}
async function matches(c){const {data,error}=await db.from('matches').select('*').eq('player_user_id',S.user.id).order('created_at',{ascending:false}).limit(30);if(error)throw error;c.innerHTML=`<section class="panel"><div class="panel-head"><h3>MATCH REGISTER</h3></div>${(data||[]).map(m=>`<div class="game-row"><div><strong>Match ${esc(m.id.slice(0,8))}</strong><span>${date(m.created_at)}</span></div><b>${esc(m.status)}</b></div>`).join('')||'<div class="empty">No matches registered.</div>'}</section>`}
async function profile(c){c.innerHTML=`<section class="panel"><div class="panel-head"><h3>PERSONNEL DOSSIER</h3></div><form id="profileForm" class="form-grid"><label>CALLSIGN<input id="pName" value="${esc(S.profile.display_name)}" required></label><label>PRIMARY FACTION<select id="pFaction"><option value="">Unassigned</option>${FACTIONS.map(f=>`<option ${S.player.primary_faction===f?'selected':''}>${f}</option>`).join('')}</select></label><label class="wide">BIO<textarea id="pBio">${esc(S.profile.bio||'')}</textarea></label><div class="wide"><button class="primary">SAVE DOSSIER</button></div></form></section>`;$('#profileForm').onsubmit=saveProfile}
async function saveProfile(e){e.preventDefault();const name=$('#pName').value.trim(),faction=$('#pFaction').value||null,bio=$('#pBio').value.trim()||null;notice('SAVING…');const a=await db.from('profiles').update({display_name:name,bio}).eq('id',S.user.id);if(a.error)return notice(a.error.message,'error');const b=await db.from('players').update({display_name:name,primary_faction:faction,updated_at:new Date().toISOString()}).eq('user_id',S.user.id);if(b.error)return notice(b.error.message,'error');S.profile.display_name=name;S.profile.bio=bio;S.player.display_name=name;S.player.primary_faction=faction;notice('DOSSIER UPDATED.','success');setTimeout(renderShell,500);setTimeout(renderView,550)}
function openModal(html){const m=$('#modal');m.hidden=false;m.innerHTML=`<div class="modal-card">${html}</div>`}
function closeModal(){const m=$('#modal');m.hidden=true;m.innerHTML=''}
function openBattle(){openModal(`<div class="panel-head"><h3>RECORD BATTLE</h3><button class="secondary" id="closeModal">CLOSE</button></div><form id="battleForm" class="form-grid"><label>OPPONENT<input id="opponent" required></label><label>RESULT<select id="result"><option value="win">VICTORY</option><option value="loss">DEFEAT</option><option value="draw">DRAW</option></select></label><label>YOUR FACTION<select id="yourFaction">${FACTIONS.map(f=>`<option ${S.player.primary_faction===f?'selected':''}>${f}</option>`).join('')}</select></label><label>OPPONENT FACTION<select id="oppFaction"><option value="">Unknown</option>${FACTIONS.map(f=>`<option>${f}</option>`).join('')}</select></label><label>YOUR VP<input id="yourVp" type="number" min="0"></label><label>OPPONENT VP<input id="oppVp" type="number" min="0"></label><label>MISSION<input id="mission"></label><label class="wide">NOTES<textarea id="notes"></textarea></label><div class="wide"><button class="primary">SAVE BATTLE REPORT</button></div></form>`);$('#closeModal').onclick=closeModal;$('#battleForm').onsubmit=saveBattle}
async function saveBattle(e){e.preventDefault();const result=$('#result').value;const row={owner_user_id:S.user.id,opponent_name:$('#opponent').value.trim(),player_faction:$('#yourFaction').value,opponent_faction:$('#oppFaction').value||null,result,player_score:$('#yourVp').value?Number($('#yourVp').value):null,opponent_score:$('#oppVp').value?Number($('#oppVp').value):null,mission:$('#mission').value.trim()||null,notes:$('#notes').value.trim()||null,played_at:new Date().toISOString()};const {data,error}=await db.from('games').insert(row).select().single();if(error)return alert(error.message);const next={games_played:(S.player.games_played||0)+1,wins:(S.player.wins||0)+(result==='win'?1:0),losses:(S.player.losses||0)+(result==='loss'?1:0),updated_at:new Date().toISOString()};const u=await db.from('players').update(next).eq('user_id',S.user.id);if(u.error)return alert(u.error.message);await db.from('matches').insert({game_id:data.id,player_user_id:S.user.id,status:'completed'});S.player={...S.player,...next};closeModal();await renderView()}
function openGroupCreate(){openModal(`<div class="panel-head"><h3>CREATE BATTLE GROUP</h3><button class="secondary" id="closeModal">CLOSE</button></div><form id="groupForm"><label>GROUP NAME<input id="groupName" maxlength="60" required></label><button class="primary">CREATE GROUP</button></form>`);$('#closeModal').onclick=closeModal;$('#groupForm').onsubmit=async e=>{e.preventDefault();const name=$('#groupName').value.trim(),code=Math.random().toString(36).slice(2,8).toUpperCase();const {data,error}=await db.from('groups').insert({name,invite_code:code,owner_user_id:S.user.id}).select().single();if(error)return alert(error.message);await db.from('group_members').insert({group_id:data.id,user_id:S.user.id,role:'owner'});closeModal();await renderView()}}
function openGroupJoin(){openModal(`<div class="panel-head"><h3>JOIN BATTLE GROUP</h3><button class="secondary" id="closeModal">CLOSE</button></div><form id="joinForm"><label>INVITE CODE<input id="invite" maxlength="12" required></label><button class="primary">JOIN GROUP</button></form>`);$('#closeModal').onclick=closeModal;$('#joinForm').onsubmit=async e=>{e.preventDefault();const {data:g,error}=await db.from('groups').select('id').eq('invite_code',$('#invite').value.trim().toUpperCase()).maybeSingle();if(error)return alert(error.message);if(!g)return alert('Invite code not found.');const r=await db.from('group_members').insert({group_id:g.id,user_id:S.user.id,role:'member'});if(r.error)return alert(r.error.message);closeModal();await renderView()}}
init();